export const RoomTariff = {
  'STANDARD' : 'STANDARD',
  'SUPERIOR' : 'SUPERIOR',
  'DELUXE' : 'DELUXE',
  'SUPERIOR_IMPROVED' : 'SUPERIOR_IMPROVED',
  'STANDARD_IMPROVED' : 'STANDARD_IMPROVED',
  'NONE' : 'NONE'
}
